# DO NOT CHANGE THIS FILE!!!
# CHANGED THIS SCRIPT -> YOUR SUBMISSION IS NOT ACCEPTED
image: se-gitlab.inf.tu-dresden.de:5001/staff/sft-lab/sft-dev:sftlab

build:
  stage: build
  tags:
    - docker
    - many-cores
  script: make
  artifacts:
    paths:
      - ./*.o
    expire_in: 10 mins

test:
  stage: test
  tags:
    - docker
    - many-cores
  script:
    - /grader/run_grader.sh $(pwd) lab-3-robust

# DO NOT CHANGE THIS FILE!!!
# CHANGED THIS SCRIPT -> YOUR SUBMISSION IS NOT ACCEPTED
